name: Build LaTeX Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Rename PDF file
        run: mv cv.pdf Filippo-Spinella_Resume.pdf
      - name: Upload PDF artifact file
        uses: actions/upload-artifact@v3
        with:
          name: Filippo-Spinella_Resume
          path: Filippo-Spinella_Resume.pdf
      - name: Create new release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Filippo-Spinella_Resume.pdf
